version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  moodle:
    image: moodlehq/moodle-php-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - moodle-data:/var/www/html
    depends_on:
      - db
volumes:
  db-data:
  moodle-data:
