version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: password
    network_mode: bridge
    pull_policy: build
    restart: always
  moodle:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    links:
      - db:database
    volumes:
      - ./moodle-data:/var/www/html/moodledata
      - ./moodle:/var/www/html
    network_mode: bridge
    environment:
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: database
      MOODLE_DB_PORT: 3306
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: password
      MOODLE_WWW_ROOT: ${MOODLE_WWW_ROOT:-http://localhost:8080}
      MOODLE_DATA_ROOT: /var/www/moodledata
    pull_policy: build
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  db-data:
    driver: local
