version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    pull_policy: build
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password_here
      MYSQL_DATABASE: moodle
    network_mode: bridge
    volumes:
      - db-data:/var/lib/mysql
  moodle:
    pull_policy: build
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - moodle-data:/var/www/html
    command: tail -f /dev/null
    network_mode: bridge
    environment:
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: root
      MOODLE_DB_PASS: your_password_here
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  db-data:
  moodle-data:
